name: Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push WebApp Docker Image
        run: |
          docker build -t webapp -f Dockerfile .
          docker tag webapp:latest ${{ steps.login-ecr.outputs.registry }}/webapp:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/webapp:latest

      - name: Build and Push MySQL Docker Image
        run: |
          docker build -t mysql -f Dockerfile_mysql .
          docker tag mysql:latest ${{ steps.login-ecr.outputs.registry }}/mysql:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/mysql:latest

